# Generated by Django 2.2 on 2019-11-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('content', models.TextField(max_length=1024, verbose_name='评论内容')),
                ('resource_id', models.IntegerField(verbose_name='评论资源id')),
                ('resource_type', models.CharField(max_length=2, verbose_name='评论资源类型')),
                ('cre_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.IntegerField(unique=True, verbose_name='回复id')),
                ('content', models.TextField(max_length=1024, verbose_name='回复内容')),
                ('reply_type', models.CharField(max_length=2, verbose_name='回复类型')),
                ('cre_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.Comment', verbose_name='评论id')),
                ('from_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='回复用户id')),
                ('to_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
    ]
