# Generated by Django 2.2 on 2019-11-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片id')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.CharField(max_length=256, verbose_name='图片地址')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'img',
            },
        ),
    ]
