# Generated by Django 2.2 on 2019-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=10, unique=True)),
                ('uid', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField(choices=[('follow', '1'), ('un_follow', '0')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=10, unique=True)),
                ('question_content', models.CharField(max_length=40)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('question_describe', models.CharField(max_length=200)),
                ('cid', models.CharField(max_length=10)),
                ('uid', models.CharField(max_length=10)),
                ('attend_count', models.IntegerField(blank=True, default=0)),
                ('browse_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
