# Generated by Django 2.2 on 2019-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_describe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
