# Generated by Django 2.2 on 2019-11-09 14:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': '已经有人抢先了哦'}, max_length=40, unique=True, verbose_name='用户名')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(blank=True, choices=[('boy', '1'), ('girl', '0')], null=True, verbose_name='性别')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avator_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('sub_desc', models.CharField(blank=True, max_length=40, null=True, verbose_name='一句话介绍')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'db_table': 'account',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('attention_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关注id')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('status', models.CharField(choices=[('follow', '1'), ('un_follow', '0')], max_length=2, verbose_name='点赞状态')),
                ('followed_user', models.ForeignKey(db_column='followed_user_id', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_user', to=settings.AUTH_USER_MODEL, verbose_name='关注的人id')),
                ('user', models.ForeignKey(db_column='user_id', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注管理',
                'db_table': 'attention',
            },
        ),
    ]
