# Generated by Django 2.2 on 2019-11-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='话题id')),
                ('title', models.CharField(max_length=40, verbose_name='话题标题')),
                ('desc', models.TextField(max_length=1024, verbose_name='话题描述')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False, verbose_name='问题id')),
                ('title', models.CharField(max_length=40, verbose_name='问题标题')),
                ('desc', models.TextField(max_length=4000, verbose_name='问题详情描述')),
                ('photos', models.CharField(max_length=1024, verbose_name='问题图片')),
                ('topics', models.CharField(max_length=1024, verbose_name='问题相关话题')),
                ('pageviews', models.IntegerField(verbose_name='浏览量')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关注id')),
                ('resource_id', models.IntegerField(unique=True, verbose_name='关注的资源id')),
                ('resource_type', models.CharField(max_length=2, verbose_name='关注资源类型')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
    ]
