# Generated by Django 2.2 on 2019-11-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, verbose_name='关注id')),
                ('content', models.TextField(max_length=65536, verbose_name='回答内容')),
                ('photos', models.CharField(max_length=1024, verbose_name='回答图片')),
                ('cre_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Question', verbose_name='问题id')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
