# Generated by Django 2.2 on 2019-11-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章id')),
                ('title', models.CharField(max_length=40, verbose_name='文章标题')),
                ('photos', models.CharField(max_length=1024, verbose_name='文章图片')),
                ('cover', models.CharField(max_length=1024, verbose_name='文章封面')),
                ('content', models.TextField(max_length=65536, verbose_name='文章内容')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('column_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='column.Column', verbose_name='专栏id')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
